baseURL = "https://tg.svoyi.ru/"
languageCode = "ru"
defaultContentLanguage = "en"

title = "Подписаться Свои Сочи"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "СВОИ Барбершоп"
  headline = "Подписаться на наш"
  image = "/img/author.png"

links = [
  { booking = { href = "https://tg.svoyi.ru/channel", text = "Telegram канал" } },
]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"